name: Reporte de Clima Programado

on:
  schedule:
    # Las horas en GitHub Actions se calculan ESTRICTAMENTE en horario UTC.
    # Si estás en Chile (UTC-4), las 15:00 son las 19:00 UTC, y las 17:00 son las 21:00 UTC.
    # Modifica los números '19,21' según la diferencia horaria de tu país respecto a UTC.
    - cron: '0 19,21 * * *'
  workflow_dispatch: # Esto te permite ejecutar el script manualmente desde la web de GitHub para probar si funciona

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar versión de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ejecutar script de clima
      env:
        # Aquí conectamos las variables ocultas de GitHub con tu código de Python
        CIUDAD: ${{ secrets.CIUDAD }}
        API_KEY_OPENWEATHERMAP: ${{ secrets.API_KEY_OPENWEATHERMAP }}
        CORREO_REMITENTE: ${{ secrets.CORREO_REMITENTE }}
        CORREO_CONTRASENA: ${{ secrets.CORREO_CONTRASENA }}
        CORREO_DESTINATARIO: ${{ secrets.CORREO_DESTINATARIO }}
      run: python app.py
